apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: your-gcp-project-id
data:
  # General App Settings
  GINSENG_MODE: "production"
  LOG_LEVEL: "info"

  # Core API Database Settings
  DB_USER: "user"
  DB_PASSWORD: "your-db-password"
  DB_NAME: "dbname"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"

  # Core API JWT Settings
  JWT_SECRET_KEY: "your-secret-key-here-change-this-in-production"
