apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https-redirect
  namespace: your-gcp-project-id
spec:
  redirectToHttps:
    enabled: false
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
