apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: your-gcp-project-id
resources:
  - namespace.yaml
  - configmap.yaml
  - gcp-ocr-credentials-secret.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - backend-config.yaml
  - frontend-config.yaml
  - core-api-deployment.yaml
  - core-api-service.yaml
  - ocr-processor-deployment.yaml
  - ocr-processor-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - managed-certificate.yaml
  - ingress.yaml
  - cronjob.yaml
  - promotion-cronjob.yaml
