apiVersion: v1
kind: Service
metadata:
  name: ocr-processor
  namespace: e-zuka-connect
spec:
  selector:
    app: ocr-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
