apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-gcp-project-id-ingress
  namespace: your-gcp-project-id
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "your-gcp-project-id.com" # my domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: core-api
            port:
              number: 80
